title: Deepali Pandey
logo: /assets/img/headshot_circle.png 
description: Data Analyst | Machine Learning | Python | SQL | Data Visualization
show_downloads: true
theme: jekyll-theme-minimal

collection:
  projects:
    output: true
    permalink: /:collection/:name/
