title: Deepali Pandey
logo: /assets/img/headshot_circle.png
description: Data Analyst | Machine Learning | Python | SQL | Data Visualization
theme: jekyll-theme-minimal

baseurl: "/potfolio"
collections:
  projects:
    output: true
    permalink: /projects/:name/
